"""shared analyzer agent per company

Revision ID: 70f1498e21bd
Revises: b5a794209f0a
Create Date: 2026-07-13 14:22:43.997835
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '70f1498e21bd'
down_revision: Union[str, None] = 'b5a794209f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('domain', sa.String(length=255), nullable=True))
    op.add_column('company', sa.Column('analyzer_agent_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'analyzer_agent_id')
    op.drop_column('company', 'domain')
    # ### end Alembic commands ###
