"""initial schema

Revision ID: b5a794209f0a
Revises: 
Create Date: 2026-07-13 12:57:56.548400
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b5a794209f0a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('admin_email', sa.String(length=320), nullable=False),
    sa.Column('ai_labs_org_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('ai_labs_user_id', sa.String(length=64), nullable=False),
    sa.Column('ai_labs_agent_id', sa.Integer(), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('api_key_masked', sa.String(length=64), nullable=True),
    sa.Column('outlook_connected', sa.Boolean(), nullable=False),
    sa.Column('provider_email', sa.String(length=320), nullable=True),
    sa.Column('needs_reprovision', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'email', name='uq_employee_company_email')
    )
    op.create_index(op.f('ix_employee_company_id'), 'employee', ['company_id'], unique=False)
    op.create_index(op.f('ix_employee_email'), 'employee', ['email'], unique=False)
    op.create_table('mailbox_snapshot',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hour_bucket', sa.String(length=20), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('ai_labs_session_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'hour_bucket', name='uq_snapshot_employee_hour')
    )
    op.create_index(op.f('ix_mailbox_snapshot_employee_id'), 'mailbox_snapshot', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mailbox_snapshot_employee_id'), table_name='mailbox_snapshot')
    op.drop_table('mailbox_snapshot')
    op.drop_index(op.f('ix_employee_email'), table_name='employee')
    op.drop_index(op.f('ix_employee_company_id'), table_name='employee')
    op.drop_table('employee')
    op.drop_table('company')
    # ### end Alembic commands ###
